CREATE TABLE SYS.ANHANSU(
    MANV CHAR(5) NOT NULL,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI CHAR(1) NOT NULL,
    NGSINH DATE,
    PHUCAP NUMBER,
    DT VARCHAR2(12),
    VAITRO VARCHAR2(12) NOT NULL,
    MADV VARCHAR2(5) NOT NULL,
    CHECK (PHAI IN ('M','F')),
    PRIMARY KEY(MANV)
);

CREATE TABLE SYS.SINHVIEN(
    MASV CHAR(5) NOT NULL,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI CHAR(1) NOT NULL,
    NGSINH DATE,
    DCHI VARCHAR2(50),
    DT VARCHAR2(12),
    MACT VARCHAR(5) NOT NULL,
    MANGANH VARCHAR(5) NOT NULL,
    SOTCTL INTEGER NOT NULL,
    DTBTL NUMBER NOT NULL,
    CHECK (PHAI IN ('M','F')),
    PRIMARY KEY(MASV)
);

CREATE TABLE SYS.DONVI(
    MADV CHAR(5) NOT NULL,
    TENDV VARCHAR2(50) NOT NULL,
    TRGDV CHAR(5) NOT NULL,
    PRIMARY KEY(MADV),
    CONSTRAINT FK_DONVI_TRGDV FOREIGN KEY (TRGDV) REFERENCES NHANSU (MANV)
);

CREATE TABLE SYS.HOCPHAN(
    MAHP CHAR(5) NOT NULL,
    TENHP VARCHAR2(50) NOT NULL,
    SOTC INTEGER NOT NULL,
    STLT INTEGER NOT NULL,
    STTH INTEGER NOT NULL,
    SOSVTD INTEGER NOT NULL,
    MADV CHAR(5) NOT NULL,
    PRIMARY KEY(MAHP),
    CONSTRAINT FK_HOCPHAN_MADV FOREIGN KEY (MADV) REFERENCES DONVI (MADV)
);

CREATE TABLE SYS.KHMO(
    MAHP CHAR(5) NOT NULL,
    HK INTEGER NOT NULL,
    NAM INTEGER NOT NULL,
    MACT VARCHAR(4) NOT NULL,
    CHECK (MACT IN ('CQ','CTTT','CLC','VP')),
    PRIMARY KEY(MAHP, HK, NAM, MACT),
    CONSTRAINT FK_KHMO_MAHP FOREIGN KEY (MAHP) REFERENCES HOCPHAN (MAHP)
);

CREATE TABLE SYS.PHANCONG(
    MAGV CHAR(5) NOT NULL,
    MAHP CHAR(5) NOT NULL,
    HK INTEGER NOT NULL,
    NAM INTEGER NOT NULL,
    MACT VARCHAR(4) NOT NULL,
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT),
    CONSTRAINT FK_PHANCONG_MAGV FOREIGN KEY (MAGV) REFERENCES NHANSU (MANV),
    CONSTRAINT FK_PHANCONG_KHMO FOREIGN KEY (MAHP, HK, NAM, MACT) 
    REFERENCES KHMO (MAHP, HK, NAM, MACT)
);

CREATE TABLE SYS.DANGKY(
    MASV CHAR(5) NOT NULL,
    MAHP CHAR(5) NOT NULL,
    HK INTEGER NOT NULL,
    NAM INTEGER NOT NULL,
    MACT VARCHAR(4) NOT NULL,
    DIEMTH NUMBER,
    DIEMQT NUMBER,
    DIEMCK NUMBER,
    DIEMTK NUMBER,
    PRIMARY KEY(MASV, MAHP, HK, NAM, MACT),
    CONSTRAINT FK_DANGKY_MASV FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV),
    CONSTRAINT FK_DANGKY_PHANCONG FOREIGN KEY (MASV, MAHP, HK, NAM, MACT) 
    REFERENCES DANGKY (MASV, MAHP, HK, NAM, MACT)
);

